pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
            bat 'mvn -f C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline/selenium-sample-master/pom.xml clean compile'
         }
      }
      stage('Test'){
          steps{
              bat 'mvn -f C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline/selenium-sample-master/pom.xml  clean install'
              cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
              }
      }
      stage('Archive'){
          steps{
              archiveArtifacts 'mvn -f C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline/selenium-sample-master/target/*.jar'
          }
      }
   }
}
