pipeline {
    agent any

    stages {
        stage('Build') {
         steps {
            bat 'mvn -f  C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline2/BDD_YOUTUBE_ENGLISH/pom.xml clean compile'
         }
      }
      stage('Test'){
          steps{
              bat 'mvn -f C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline2/BDD_YOUTUBE_ENGLISH/pom.xml clean install'
              cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
              }
      }


        
         stage ('Cucumber Reports') {
            steps {
                cucumber buildStatus: "STABLE",
                fileIncludePattern: "**/result.json",
                jsonReportDirectory:'C:/ProgramData/Jenkins/.jenkins/workspace/Groovy_Pipeline2/BDD_YOUTUBE_ENGLISH/BDD_YOUTUBE_ENGLISH/src/test/java/Test/result.json'
                }
            }
        }
        
    
}